### ISSUE TITLE
趋势部分的下单价格没看明白

### ISSUE THREAD

**Issue by louis-cai** [richox/okcoin-leeks-reaper#3]
`def tradePrice = bull ? bidPrice : askPrice
                    trading = true

                    while (tradeAmount >= 0.1) {
                        def orderId = bull  // 提单
                            ? trader1.trade("btc_cny", Type.BUY,  bidPrice, tradeAmount).orderId
                            : trader1.trade("btc_cny", Type.SELL, askPrice, tradeAmount).orderId
`
下单的时候没有用tradePrice，后面虽然循环后，但是tradePrice还是没用，那这里声明tradePrice有什么用呢？

**Comment by richox** [comment]
用来在重试交易的时候削减tradeAmount的

**Comment by louis-cai** [comment]
后面看明白了，谢谢
